### ISSUE TITLE
Any room on builtwithjigsaw.com for a boilerplate/template?

### ISSUE THREAD

**Issue by raniesantos** [tightenco/builtwithjigsaw#31]
I know [Matt mentioned Jigsaw Generators](https://github.com/tightenco/jigsaw/issues/236) would eventually be added, but my hands were itching to build [this blog template](https://github.com/raniesantos/jigsaw-netlify-starter) early.

Its not a live site or an article, so I wonder if I could still get this added in?

**Comment by mattstauffer** [comment]
@raniesantos what do you think about writing a quick blog post describing it, and then we can link that?

**Comment by raniesantos** [comment]
Ok thanks, I'll either make a blog post, or deploy a demo of it so that it fits in one of the two categories.
