### ISSUE TITLE
I found this because it uses the template I made

### ISSUE THREAD

**Issue by raniesantos** [tightenco/builtwithjigsaw#44]
https://github.com/mascarell/mascarell

**Comment by anthonyterrell** [comment]
Hey @raniesantos 👋,

I'm not quite sure which template you're referring to, but if there's something referencing your work on https://builtwithjigsaw.com/ incorrectly you can open up an issue and let us know. 

Cheers!

**Comment by mattstauffer** [comment]
@anthonyterrell No, he's saying this `mascarell` project uses Ranie's original template, and we should add it as a site on builtwithjigsaw.

**Comment by raniesantos** [comment]
What Matt said.
